[2023-03-27 21:10:05,520] {processor.py:153} INFO - Started process (PID=6087) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:10:05,520] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:10:05,520] {logging_mixin.py:115} INFO - [2023-03-27 21:10:05,520] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:10:05,533] {logging_mixin.py:115} INFO - [2023-03-27 21:10:05,533] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:10:05,533] {logging_mixin.py:115} INFO - [2023-03-27 21:10:05,533] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:10:05,533] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:10:05,553] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-27 21:10:57,625] {processor.py:153} INFO - Started process (PID=6174) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:10:57,626] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:10:57,626] {logging_mixin.py:115} INFO - [2023-03-27 21:10:57,626] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:10:57,639] {logging_mixin.py:115} INFO - [2023-03-27 21:10:57,639] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:10:57,639] {logging_mixin.py:115} INFO - [2023-03-27 21:10:57,639] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:10:57,639] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:10:57,659] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:11:48,664] {processor.py:153} INFO - Started process (PID=6264) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:11:48,665] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:11:48,665] {logging_mixin.py:115} INFO - [2023-03-27 21:11:48,665] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:11:48,679] {logging_mixin.py:115} INFO - [2023-03-27 21:11:48,679] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:11:48,679] {logging_mixin.py:115} INFO - [2023-03-27 21:11:48,679] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:11:48,679] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:11:48,700] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-03-27 21:12:59,309] {processor.py:153} INFO - Started process (PID=6377) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:12:59,310] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:12:59,310] {logging_mixin.py:115} INFO - [2023-03-27 21:12:59,310] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:12:59,323] {logging_mixin.py:115} INFO - [2023-03-27 21:12:59,323] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:12:59,323] {logging_mixin.py:115} INFO - [2023-03-27 21:12:59,323] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:12:59,323] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:12:59,343] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:14:06,723] {processor.py:153} INFO - Started process (PID=6493) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:14:06,724] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:14:06,724] {logging_mixin.py:115} INFO - [2023-03-27 21:14:06,724] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:14:06,738] {logging_mixin.py:115} INFO - [2023-03-27 21:14:06,738] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:14:06,738] {logging_mixin.py:115} INFO - [2023-03-27 21:14:06,738] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:14:06,738] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:14:06,757] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:15:04,910] {processor.py:153} INFO - Started process (PID=6591) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:15:04,911] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:15:04,911] {logging_mixin.py:115} INFO - [2023-03-27 21:15:04,911] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:15:04,925] {logging_mixin.py:115} INFO - [2023-03-27 21:15:04,925] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:15:04,925] {logging_mixin.py:115} INFO - [2023-03-27 21:15:04,925] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:15:04,925] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:15:04,944] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:16:11,214] {processor.py:153} INFO - Started process (PID=6700) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:16:11,214] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:16:11,215] {logging_mixin.py:115} INFO - [2023-03-27 21:16:11,215] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:16:11,228] {logging_mixin.py:115} INFO - [2023-03-27 21:16:11,227] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:16:11,228] {logging_mixin.py:115} INFO - [2023-03-27 21:16:11,228] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:16:11,228] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:16:11,247] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:17:16,515] {processor.py:153} INFO - Started process (PID=6808) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:17:16,515] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:17:16,515] {logging_mixin.py:115} INFO - [2023-03-27 21:17:16,515] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:17:16,528] {logging_mixin.py:115} INFO - [2023-03-27 21:17:16,528] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:17:16,528] {logging_mixin.py:115} INFO - [2023-03-27 21:17:16,528] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:17:16,528] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:17:16,547] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:18:20,394] {processor.py:153} INFO - Started process (PID=6915) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:18:20,395] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:18:20,395] {logging_mixin.py:115} INFO - [2023-03-27 21:18:20,395] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:18:20,409] {logging_mixin.py:115} INFO - [2023-03-27 21:18:20,409] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:18:20,409] {logging_mixin.py:115} INFO - [2023-03-27 21:18:20,409] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:18:20,409] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:18:20,428] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:19:26,009] {processor.py:153} INFO - Started process (PID=7030) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:19:26,009] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:19:26,010] {logging_mixin.py:115} INFO - [2023-03-27 21:19:26,010] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:19:26,023] {logging_mixin.py:115} INFO - [2023-03-27 21:19:26,023] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:19:26,023] {logging_mixin.py:115} INFO - [2023-03-27 21:19:26,023] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:19:26,023] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:19:26,042] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:20:33,172] {processor.py:153} INFO - Started process (PID=7139) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:20:33,172] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:20:33,172] {logging_mixin.py:115} INFO - [2023-03-27 21:20:33,172] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:20:33,185] {logging_mixin.py:115} INFO - [2023-03-27 21:20:33,185] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:20:33,185] {logging_mixin.py:115} INFO - [2023-03-27 21:20:33,185] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:20:33,185] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:20:33,204] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-27 21:21:40,993] {processor.py:153} INFO - Started process (PID=7250) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:21:40,993] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:21:40,993] {logging_mixin.py:115} INFO - [2023-03-27 21:21:40,993] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:21:41,006] {logging_mixin.py:115} INFO - [2023-03-27 21:21:41,006] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:21:41,006] {logging_mixin.py:115} INFO - [2023-03-27 21:21:41,006] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:21:41,006] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:21:41,025] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:22:48,913] {processor.py:153} INFO - Started process (PID=7364) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:22:48,913] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:22:48,913] {logging_mixin.py:115} INFO - [2023-03-27 21:22:48,913] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:22:48,926] {logging_mixin.py:115} INFO - [2023-03-27 21:22:48,926] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:22:48,926] {logging_mixin.py:115} INFO - [2023-03-27 21:22:48,926] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:22:48,926] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:22:48,945] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:23:54,082] {processor.py:153} INFO - Started process (PID=7476) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:23:54,083] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:23:54,083] {logging_mixin.py:115} INFO - [2023-03-27 21:23:54,083] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:23:54,096] {logging_mixin.py:115} INFO - [2023-03-27 21:23:54,096] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:23:54,096] {logging_mixin.py:115} INFO - [2023-03-27 21:23:54,096] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:23:54,096] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:23:54,115] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:25:00,699] {processor.py:153} INFO - Started process (PID=7615) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:25:00,700] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:25:00,700] {logging_mixin.py:115} INFO - [2023-03-27 21:25:00,700] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:25:00,713] {logging_mixin.py:115} INFO - [2023-03-27 21:25:00,713] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:25:00,713] {logging_mixin.py:115} INFO - [2023-03-27 21:25:00,713] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:25:00,713] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:25:00,732] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-27 21:26:05,485] {processor.py:153} INFO - Started process (PID=7736) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:26:05,485] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:26:05,485] {logging_mixin.py:115} INFO - [2023-03-27 21:26:05,485] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:26:05,499] {logging_mixin.py:115} INFO - [2023-03-27 21:26:05,498] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:26:05,499] {logging_mixin.py:115} INFO - [2023-03-27 21:26:05,499] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:26:05,499] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:26:05,518] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-27 21:27:14,018] {processor.py:153} INFO - Started process (PID=7848) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:27:14,018] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:27:14,018] {logging_mixin.py:115} INFO - [2023-03-27 21:27:14,018] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:27:14,031] {logging_mixin.py:115} INFO - [2023-03-27 21:27:14,031] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:27:14,031] {logging_mixin.py:115} INFO - [2023-03-27 21:27:14,031] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:27:14,031] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:27:14,050] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:28:18,326] {processor.py:153} INFO - Started process (PID=7958) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:28:18,327] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:28:18,327] {logging_mixin.py:115} INFO - [2023-03-27 21:28:18,327] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:28:18,339] {logging_mixin.py:115} INFO - [2023-03-27 21:28:18,339] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:28:18,339] {logging_mixin.py:115} INFO - [2023-03-27 21:28:18,339] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:28:18,339] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:28:18,358] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:29:20,881] {processor.py:153} INFO - Started process (PID=8076) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:29:20,881] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:29:20,881] {logging_mixin.py:115} INFO - [2023-03-27 21:29:20,881] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:29:20,894] {logging_mixin.py:115} INFO - [2023-03-27 21:29:20,894] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:29:20,894] {logging_mixin.py:115} INFO - [2023-03-27 21:29:20,894] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:29:20,894] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:29:20,913] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:30:27,372] {processor.py:153} INFO - Started process (PID=8219) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:30:27,373] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:30:27,373] {logging_mixin.py:115} INFO - [2023-03-27 21:30:27,373] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:30:27,386] {logging_mixin.py:115} INFO - [2023-03-27 21:30:27,385] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:30:27,386] {logging_mixin.py:115} INFO - [2023-03-27 21:30:27,386] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:30:27,386] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:30:27,405] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-27 21:31:30,231] {processor.py:153} INFO - Started process (PID=8324) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:31:30,231] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:31:30,231] {logging_mixin.py:115} INFO - [2023-03-27 21:31:30,231] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:31:30,244] {logging_mixin.py:115} INFO - [2023-03-27 21:31:30,244] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:31:30,244] {logging_mixin.py:115} INFO - [2023-03-27 21:31:30,244] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:31:30,244] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:31:30,263] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:32:36,101] {processor.py:153} INFO - Started process (PID=8433) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:32:36,101] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:32:36,101] {logging_mixin.py:115} INFO - [2023-03-27 21:32:36,101] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:32:36,114] {logging_mixin.py:115} INFO - [2023-03-27 21:32:36,114] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:32:36,114] {logging_mixin.py:115} INFO - [2023-03-27 21:32:36,114] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:32:36,114] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:32:36,133] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:33:43,932] {processor.py:153} INFO - Started process (PID=8549) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:33:43,932] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:33:43,932] {logging_mixin.py:115} INFO - [2023-03-27 21:33:43,932] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:33:43,944] {logging_mixin.py:115} INFO - [2023-03-27 21:33:43,944] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:33:43,945] {logging_mixin.py:115} INFO - [2023-03-27 21:33:43,945] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:33:43,945] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:33:43,964] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-27 21:59:25,287] {processor.py:153} INFO - Started process (PID=8686) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:59:25,288] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 21:59:25,288] {logging_mixin.py:115} INFO - [2023-03-27 21:59:25,288] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:59:25,317] {logging_mixin.py:115} INFO - [2023-03-27 21:59:25,316] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 21:59:25,317] {logging_mixin.py:115} INFO - [2023-03-27 21:59:25,317] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 21:59:25,317] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 21:59:25,349] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-03-27 22:07:53,056] {processor.py:153} INFO - Started process (PID=8826) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 22:07:53,057] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-27 22:07:53,057] {logging_mixin.py:115} INFO - [2023-03-27 22:07:53,057] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 22:07:53,089] {logging_mixin.py:115} INFO - [2023-03-27 22:07:53,088] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-27 22:07:53,089] {logging_mixin.py:115} INFO - [2023-03-27 22:07:53,089] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-27 22:07:53,089] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-27 22:07:53,176] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.120 seconds
