[2023-03-23 22:57:42,549] {processor.py:153} INFO - Started process (PID=1831) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:57:42,550] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 22:57:42,550] {logging_mixin.py:115} INFO - [2023-03-23 22:57:42,550] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:57:42,563] {logging_mixin.py:115} INFO - [2023-03-23 22:57:42,563] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 22:57:42,563] {logging_mixin.py:115} INFO - [2023-03-23 22:57:42,563] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 22:57:42,563] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:57:42,582] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-23 22:58:32,056] {processor.py:153} INFO - Started process (PID=1869) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:58:32,057] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 22:58:32,057] {logging_mixin.py:115} INFO - [2023-03-23 22:58:32,057] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:58:32,070] {logging_mixin.py:115} INFO - [2023-03-23 22:58:32,070] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 22:58:32,070] {logging_mixin.py:115} INFO - [2023-03-23 22:58:32,070] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 22:58:32,070] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:58:32,089] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-23 22:59:32,347] {processor.py:153} INFO - Started process (PID=1920) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:59:32,347] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 22:59:32,348] {logging_mixin.py:115} INFO - [2023-03-23 22:59:32,348] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:59:32,361] {logging_mixin.py:115} INFO - [2023-03-23 22:59:32,361] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 22:59:32,361] {logging_mixin.py:115} INFO - [2023-03-23 22:59:32,361] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 22:59:32,361] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 22:59:32,383] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-03-23 23:00:37,063] {processor.py:153} INFO - Started process (PID=1978) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:00:37,064] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:00:37,064] {logging_mixin.py:115} INFO - [2023-03-23 23:00:37,064] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:00:37,077] {logging_mixin.py:115} INFO - [2023-03-23 23:00:37,077] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:00:37,077] {logging_mixin.py:115} INFO - [2023-03-23 23:00:37,077] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:00:37,077] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:00:37,096] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-23 23:01:30,053] {processor.py:153} INFO - Started process (PID=2025) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:01:30,054] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:01:30,054] {logging_mixin.py:115} INFO - [2023-03-23 23:01:30,054] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:01:30,067] {logging_mixin.py:115} INFO - [2023-03-23 23:01:30,067] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:01:30,067] {logging_mixin.py:115} INFO - [2023-03-23 23:01:30,067] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:01:30,067] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:01:30,086] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-23 23:02:49,382] {processor.py:153} INFO - Started process (PID=2101) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:02:49,382] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:02:49,383] {logging_mixin.py:115} INFO - [2023-03-23 23:02:49,383] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:02:49,397] {logging_mixin.py:115} INFO - [2023-03-23 23:02:49,397] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:02:49,397] {logging_mixin.py:115} INFO - [2023-03-23 23:02:49,397] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:02:49,397] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:02:49,417] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-03-23 23:03:40,658] {processor.py:153} INFO - Started process (PID=2142) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:03:40,659] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:03:40,659] {logging_mixin.py:115} INFO - [2023-03-23 23:03:40,659] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:03:40,672] {logging_mixin.py:115} INFO - [2023-03-23 23:03:40,672] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:03:40,672] {logging_mixin.py:115} INFO - [2023-03-23 23:03:40,672] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:03:40,672] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:03:40,692] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-23 23:04:37,458] {processor.py:153} INFO - Started process (PID=2185) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:04:37,459] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:04:37,459] {logging_mixin.py:115} INFO - [2023-03-23 23:04:37,459] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:04:37,472] {logging_mixin.py:115} INFO - [2023-03-23 23:04:37,472] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:04:37,472] {logging_mixin.py:115} INFO - [2023-03-23 23:04:37,472] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:04:37,473] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:04:37,492] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-23 23:05:34,204] {processor.py:153} INFO - Started process (PID=2230) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:05:34,204] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:05:34,204] {logging_mixin.py:115} INFO - [2023-03-23 23:05:34,204] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:05:34,218] {logging_mixin.py:115} INFO - [2023-03-23 23:05:34,217] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:05:34,218] {logging_mixin.py:115} INFO - [2023-03-23 23:05:34,218] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:05:34,218] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:05:34,236] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-23 23:06:51,806] {processor.py:153} INFO - Started process (PID=2301) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:06:51,806] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:06:51,807] {logging_mixin.py:115} INFO - [2023-03-23 23:06:51,807] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:06:51,820] {logging_mixin.py:115} INFO - [2023-03-23 23:06:51,819] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:06:51,820] {logging_mixin.py:115} INFO - [2023-03-23 23:06:51,820] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:06:51,820] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:06:51,839] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-23 23:08:12,391] {processor.py:153} INFO - Started process (PID=2372) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:08:12,392] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:08:12,392] {logging_mixin.py:115} INFO - [2023-03-23 23:08:12,392] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:08:12,404] {logging_mixin.py:115} INFO - [2023-03-23 23:08:12,404] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:08:12,404] {logging_mixin.py:115} INFO - [2023-03-23 23:08:12,404] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:08:12,405] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:08:12,425] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-23 23:09:04,517] {processor.py:153} INFO - Started process (PID=2410) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:09:04,518] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:09:04,518] {logging_mixin.py:115} INFO - [2023-03-23 23:09:04,518] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:09:04,531] {logging_mixin.py:115} INFO - [2023-03-23 23:09:04,530] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:09:04,531] {logging_mixin.py:115} INFO - [2023-03-23 23:09:04,531] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:09:04,531] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:09:04,550] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-23 23:09:55,751] {processor.py:153} INFO - Started process (PID=2450) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:09:55,751] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:09:55,751] {logging_mixin.py:115} INFO - [2023-03-23 23:09:55,751] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:09:55,763] {logging_mixin.py:115} INFO - [2023-03-23 23:09:55,763] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:09:55,763] {logging_mixin.py:115} INFO - [2023-03-23 23:09:55,763] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:09:55,763] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:09:55,782] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-23 23:10:57,288] {processor.py:153} INFO - Started process (PID=2494) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:10:57,289] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-23 23:10:57,289] {logging_mixin.py:115} INFO - [2023-03-23 23:10:57,289] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:10:57,303] {logging_mixin.py:115} INFO - [2023-03-23 23:10:57,303] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-23 23:10:57,303] {logging_mixin.py:115} INFO - [2023-03-23 23:10:57,303] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-23 23:10:57,303] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-23 23:10:57,322] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
