[2023-03-29 22:19:19,745] {processor.py:153} INFO - Started process (PID=5234) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:19:19,745] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:19:19,745] {logging_mixin.py:115} INFO - [2023-03-29 22:19:19,745] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:19:19,759] {logging_mixin.py:115} INFO - [2023-03-29 22:19:19,759] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:19:19,759] {logging_mixin.py:115} INFO - [2023-03-29 22:19:19,759] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:19:19,759] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:19:19,779] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:20:11,917] {processor.py:153} INFO - Started process (PID=5337) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:20:11,918] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:20:11,918] {logging_mixin.py:115} INFO - [2023-03-29 22:20:11,918] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:20:11,932] {logging_mixin.py:115} INFO - [2023-03-29 22:20:11,931] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:20:11,932] {logging_mixin.py:115} INFO - [2023-03-29 22:20:11,932] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:20:11,932] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:20:11,951] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:21:04,353] {processor.py:153} INFO - Started process (PID=5424) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:21:04,353] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:21:04,353] {logging_mixin.py:115} INFO - [2023-03-29 22:21:04,353] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:21:04,367] {logging_mixin.py:115} INFO - [2023-03-29 22:21:04,366] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:21:04,367] {logging_mixin.py:115} INFO - [2023-03-29 22:21:04,367] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:21:04,367] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:21:04,386] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:22:10,114] {processor.py:153} INFO - Started process (PID=5554) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:22:10,115] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:22:10,115] {logging_mixin.py:115} INFO - [2023-03-29 22:22:10,115] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:22:10,128] {logging_mixin.py:115} INFO - [2023-03-29 22:22:10,128] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:22:10,128] {logging_mixin.py:115} INFO - [2023-03-29 22:22:10,128] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:22:10,129] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:22:10,148] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:23:17,505] {processor.py:153} INFO - Started process (PID=5669) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:23:17,506] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:23:17,506] {logging_mixin.py:115} INFO - [2023-03-29 22:23:17,506] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:23:17,519] {logging_mixin.py:115} INFO - [2023-03-29 22:23:17,519] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:23:17,519] {logging_mixin.py:115} INFO - [2023-03-29 22:23:17,519] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:23:17,519] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:23:17,539] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:24:25,789] {processor.py:153} INFO - Started process (PID=5794) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:24:25,790] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:24:25,790] {logging_mixin.py:115} INFO - [2023-03-29 22:24:25,790] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:24:25,803] {logging_mixin.py:115} INFO - [2023-03-29 22:24:25,803] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:24:25,803] {logging_mixin.py:115} INFO - [2023-03-29 22:24:25,803] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:24:25,803] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:24:25,822] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:25:12,000] {processor.py:153} INFO - Started process (PID=5882) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:25:12,001] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:25:12,001] {logging_mixin.py:115} INFO - [2023-03-29 22:25:12,001] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:25:12,013] {logging_mixin.py:115} INFO - [2023-03-29 22:25:12,013] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:25:12,014] {logging_mixin.py:115} INFO - [2023-03-29 22:25:12,014] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:25:12,014] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:25:12,033] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:26:20,296] {processor.py:153} INFO - Started process (PID=5993) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:26:20,296] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:26:20,296] {logging_mixin.py:115} INFO - [2023-03-29 22:26:20,296] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:26:20,309] {logging_mixin.py:115} INFO - [2023-03-29 22:26:20,309] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:26:20,309] {logging_mixin.py:115} INFO - [2023-03-29 22:26:20,309] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:26:20,309] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:26:20,328] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:27:29,467] {processor.py:153} INFO - Started process (PID=6132) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:27:29,468] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:27:29,468] {logging_mixin.py:115} INFO - [2023-03-29 22:27:29,468] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:27:29,481] {logging_mixin.py:115} INFO - [2023-03-29 22:27:29,481] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:27:29,481] {logging_mixin.py:115} INFO - [2023-03-29 22:27:29,481] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:27:29,482] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:27:29,501] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:28:39,249] {processor.py:153} INFO - Started process (PID=6247) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:28:39,250] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:28:39,250] {logging_mixin.py:115} INFO - [2023-03-29 22:28:39,250] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:28:39,263] {logging_mixin.py:115} INFO - [2023-03-29 22:28:39,263] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:28:39,263] {logging_mixin.py:115} INFO - [2023-03-29 22:28:39,263] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:28:39,263] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:28:39,282] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:29:48,656] {processor.py:153} INFO - Started process (PID=6389) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:29:48,657] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:29:48,657] {logging_mixin.py:115} INFO - [2023-03-29 22:29:48,657] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:29:48,671] {logging_mixin.py:115} INFO - [2023-03-29 22:29:48,671] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:29:48,671] {logging_mixin.py:115} INFO - [2023-03-29 22:29:48,671] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:29:48,671] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:29:48,691] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 22:30:41,559] {processor.py:153} INFO - Started process (PID=6477) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:30:41,559] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:30:41,560] {logging_mixin.py:115} INFO - [2023-03-29 22:30:41,560] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:30:41,574] {logging_mixin.py:115} INFO - [2023-03-29 22:30:41,573] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:30:41,574] {logging_mixin.py:115} INFO - [2023-03-29 22:30:41,574] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:30:41,574] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:30:41,593] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 22:31:41,850] {processor.py:153} INFO - Started process (PID=6590) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:31:41,851] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:31:41,851] {logging_mixin.py:115} INFO - [2023-03-29 22:31:41,851] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:31:41,864] {logging_mixin.py:115} INFO - [2023-03-29 22:31:41,864] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:31:41,864] {logging_mixin.py:115} INFO - [2023-03-29 22:31:41,864] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:31:41,864] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:31:41,884] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 22:32:34,841] {processor.py:153} INFO - Started process (PID=6681) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:32:34,841] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:32:34,841] {logging_mixin.py:115} INFO - [2023-03-29 22:32:34,841] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:32:34,855] {logging_mixin.py:115} INFO - [2023-03-29 22:32:34,855] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:32:34,855] {logging_mixin.py:115} INFO - [2023-03-29 22:32:34,855] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:32:34,855] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:32:34,874] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:33:27,487] {processor.py:153} INFO - Started process (PID=6777) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:33:27,488] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:33:27,488] {logging_mixin.py:115} INFO - [2023-03-29 22:33:27,488] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:33:27,502] {logging_mixin.py:115} INFO - [2023-03-29 22:33:27,502] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:33:27,502] {logging_mixin.py:115} INFO - [2023-03-29 22:33:27,502] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:33:27,502] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:33:27,521] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 22:34:32,176] {processor.py:153} INFO - Started process (PID=6892) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:34:32,176] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:34:32,176] {logging_mixin.py:115} INFO - [2023-03-29 22:34:32,176] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:34:32,189] {logging_mixin.py:115} INFO - [2023-03-29 22:34:32,188] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:34:32,189] {logging_mixin.py:115} INFO - [2023-03-29 22:34:32,189] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:34:32,189] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:34:32,208] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:35:39,981] {processor.py:153} INFO - Started process (PID=7001) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:35:39,982] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:35:39,982] {logging_mixin.py:115} INFO - [2023-03-29 22:35:39,982] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:35:39,995] {logging_mixin.py:115} INFO - [2023-03-29 22:35:39,995] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:35:39,995] {logging_mixin.py:115} INFO - [2023-03-29 22:35:39,995] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:35:39,995] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:35:40,014] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:36:45,375] {processor.py:153} INFO - Started process (PID=7108) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:36:45,376] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:36:45,377] {logging_mixin.py:115} INFO - [2023-03-29 22:36:45,376] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:36:45,389] {logging_mixin.py:115} INFO - [2023-03-29 22:36:45,389] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:36:45,389] {logging_mixin.py:115} INFO - [2023-03-29 22:36:45,389] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:36:45,389] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:36:45,408] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:37:51,626] {processor.py:153} INFO - Started process (PID=7218) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:37:51,626] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:37:51,626] {logging_mixin.py:115} INFO - [2023-03-29 22:37:51,626] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:37:51,639] {logging_mixin.py:115} INFO - [2023-03-29 22:37:51,638] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:37:51,639] {logging_mixin.py:115} INFO - [2023-03-29 22:37:51,639] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:37:51,639] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:37:51,658] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-29 22:38:58,135] {processor.py:153} INFO - Started process (PID=7335) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:38:58,136] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:38:58,136] {logging_mixin.py:115} INFO - [2023-03-29 22:38:58,136] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:38:58,149] {logging_mixin.py:115} INFO - [2023-03-29 22:38:58,149] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:38:58,150] {logging_mixin.py:115} INFO - [2023-03-29 22:38:58,150] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:38:58,150] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:38:58,169] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:40:06,193] {processor.py:153} INFO - Started process (PID=7446) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:40:06,194] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:40:06,194] {logging_mixin.py:115} INFO - [2023-03-29 22:40:06,194] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:40:06,207] {logging_mixin.py:115} INFO - [2023-03-29 22:40:06,207] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:40:06,207] {logging_mixin.py:115} INFO - [2023-03-29 22:40:06,207] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:40:06,208] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:40:06,227] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:41:16,633] {processor.py:153} INFO - Started process (PID=7564) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:41:16,634] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:41:16,634] {logging_mixin.py:115} INFO - [2023-03-29 22:41:16,634] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:41:16,646] {logging_mixin.py:115} INFO - [2023-03-29 22:41:16,646] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:41:16,646] {logging_mixin.py:115} INFO - [2023-03-29 22:41:16,646] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:41:16,646] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:41:16,665] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:42:24,077] {processor.py:153} INFO - Started process (PID=7680) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:42:24,078] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:42:24,078] {logging_mixin.py:115} INFO - [2023-03-29 22:42:24,078] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:42:24,092] {logging_mixin.py:115} INFO - [2023-03-29 22:42:24,091] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:42:24,092] {logging_mixin.py:115} INFO - [2023-03-29 22:42:24,092] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:42:24,092] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:42:24,111] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:43:27,863] {processor.py:153} INFO - Started process (PID=7788) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:43:27,864] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:43:27,864] {logging_mixin.py:115} INFO - [2023-03-29 22:43:27,864] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:43:27,878] {logging_mixin.py:115} INFO - [2023-03-29 22:43:27,877] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:43:27,878] {logging_mixin.py:115} INFO - [2023-03-29 22:43:27,878] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:43:27,878] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:43:27,896] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:44:36,684] {processor.py:153} INFO - Started process (PID=7909) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:44:36,685] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:44:36,685] {logging_mixin.py:115} INFO - [2023-03-29 22:44:36,685] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:44:36,699] {logging_mixin.py:115} INFO - [2023-03-29 22:44:36,699] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:44:36,699] {logging_mixin.py:115} INFO - [2023-03-29 22:44:36,699] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:44:36,699] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:44:36,718] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:45:43,515] {processor.py:153} INFO - Started process (PID=8031) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:45:43,515] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:45:43,516] {logging_mixin.py:115} INFO - [2023-03-29 22:45:43,516] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:45:43,529] {logging_mixin.py:115} INFO - [2023-03-29 22:45:43,529] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:45:43,529] {logging_mixin.py:115} INFO - [2023-03-29 22:45:43,529] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:45:43,529] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:45:43,548] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:46:53,950] {processor.py:153} INFO - Started process (PID=8159) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:46:53,951] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:46:53,951] {logging_mixin.py:115} INFO - [2023-03-29 22:46:53,951] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:46:53,964] {logging_mixin.py:115} INFO - [2023-03-29 22:46:53,963] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:46:53,964] {logging_mixin.py:115} INFO - [2023-03-29 22:46:53,964] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:46:53,964] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:46:53,983] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:48:03,023] {processor.py:153} INFO - Started process (PID=8273) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:48:03,024] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:48:03,024] {logging_mixin.py:115} INFO - [2023-03-29 22:48:03,024] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:48:03,041] {logging_mixin.py:115} INFO - [2023-03-29 22:48:03,041] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:48:03,041] {logging_mixin.py:115} INFO - [2023-03-29 22:48:03,041] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:48:03,041] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:48:03,061] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-03-29 22:49:05,976] {processor.py:153} INFO - Started process (PID=8384) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:49:05,976] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:49:05,976] {logging_mixin.py:115} INFO - [2023-03-29 22:49:05,976] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:49:05,990] {logging_mixin.py:115} INFO - [2023-03-29 22:49:05,990] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:49:05,990] {logging_mixin.py:115} INFO - [2023-03-29 22:49:05,990] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:49:05,990] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:49:06,010] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:50:14,213] {processor.py:153} INFO - Started process (PID=8503) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:50:14,213] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:50:14,214] {logging_mixin.py:115} INFO - [2023-03-29 22:50:14,214] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:50:14,228] {logging_mixin.py:115} INFO - [2023-03-29 22:50:14,227] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:50:14,228] {logging_mixin.py:115} INFO - [2023-03-29 22:50:14,228] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:50:14,228] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:50:14,247] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 22:51:01,215] {processor.py:153} INFO - Started process (PID=8581) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:51:01,216] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:51:01,216] {logging_mixin.py:115} INFO - [2023-03-29 22:51:01,216] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:51:01,229] {logging_mixin.py:115} INFO - [2023-03-29 22:51:01,229] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:51:01,229] {logging_mixin.py:115} INFO - [2023-03-29 22:51:01,229] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:51:01,229] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:51:01,249] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:51:48,443] {processor.py:153} INFO - Started process (PID=8659) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:51:48,444] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:51:48,444] {logging_mixin.py:115} INFO - [2023-03-29 22:51:48,444] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:51:48,457] {logging_mixin.py:115} INFO - [2023-03-29 22:51:48,457] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:51:48,457] {logging_mixin.py:115} INFO - [2023-03-29 22:51:48,457] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:51:48,457] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:51:48,477] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:52:35,487] {processor.py:153} INFO - Started process (PID=8739) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:52:35,488] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:52:35,488] {logging_mixin.py:115} INFO - [2023-03-29 22:52:35,488] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:52:35,501] {logging_mixin.py:115} INFO - [2023-03-29 22:52:35,501] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:52:35,501] {logging_mixin.py:115} INFO - [2023-03-29 22:52:35,501] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:52:35,501] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:52:35,521] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 22:53:23,251] {processor.py:153} INFO - Started process (PID=8820) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:53:23,252] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:53:23,252] {logging_mixin.py:115} INFO - [2023-03-29 22:53:23,252] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:53:23,266] {logging_mixin.py:115} INFO - [2023-03-29 22:53:23,265] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:53:23,266] {logging_mixin.py:115} INFO - [2023-03-29 22:53:23,266] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:53:23,266] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:53:23,285] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 22:54:33,964] {processor.py:153} INFO - Started process (PID=8934) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:54:33,964] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:54:33,965] {logging_mixin.py:115} INFO - [2023-03-29 22:54:33,965] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:54:33,978] {logging_mixin.py:115} INFO - [2023-03-29 22:54:33,978] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:54:33,978] {logging_mixin.py:115} INFO - [2023-03-29 22:54:33,978] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:54:33,978] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:54:33,997] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:55:21,940] {processor.py:153} INFO - Started process (PID=9013) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:55:21,940] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:55:21,941] {logging_mixin.py:115} INFO - [2023-03-29 22:55:21,941] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:55:21,953] {logging_mixin.py:115} INFO - [2023-03-29 22:55:21,953] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:55:21,953] {logging_mixin.py:115} INFO - [2023-03-29 22:55:21,953] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:55:21,953] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:55:21,973] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:56:32,175] {processor.py:153} INFO - Started process (PID=9131) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:56:32,175] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:56:32,175] {logging_mixin.py:115} INFO - [2023-03-29 22:56:32,175] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:56:32,188] {logging_mixin.py:115} INFO - [2023-03-29 22:56:32,187] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:56:32,188] {logging_mixin.py:115} INFO - [2023-03-29 22:56:32,188] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:56:32,188] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:56:32,207] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-29 22:57:40,405] {processor.py:153} INFO - Started process (PID=9245) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:57:40,406] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:57:40,406] {logging_mixin.py:115} INFO - [2023-03-29 22:57:40,406] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:57:40,419] {logging_mixin.py:115} INFO - [2023-03-29 22:57:40,419] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:57:40,419] {logging_mixin.py:115} INFO - [2023-03-29 22:57:40,419] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:57:40,419] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:57:40,438] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 22:58:48,698] {processor.py:153} INFO - Started process (PID=9363) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:58:48,699] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:58:48,699] {logging_mixin.py:115} INFO - [2023-03-29 22:58:48,699] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:58:48,712] {logging_mixin.py:115} INFO - [2023-03-29 22:58:48,711] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:58:48,712] {logging_mixin.py:115} INFO - [2023-03-29 22:58:48,712] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:58:48,712] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:58:48,733] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 22:59:37,774] {processor.py:153} INFO - Started process (PID=9445) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:59:37,774] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 22:59:37,775] {logging_mixin.py:115} INFO - [2023-03-29 22:59:37,775] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:59:37,788] {logging_mixin.py:115} INFO - [2023-03-29 22:59:37,788] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 22:59:37,788] {logging_mixin.py:115} INFO - [2023-03-29 22:59:37,788] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 22:59:37,788] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 22:59:37,808] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:00:25,643] {processor.py:153} INFO - Started process (PID=9532) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:00:25,643] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:00:25,643] {logging_mixin.py:115} INFO - [2023-03-29 23:00:25,643] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:00:25,657] {logging_mixin.py:115} INFO - [2023-03-29 23:00:25,657] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:00:25,657] {logging_mixin.py:115} INFO - [2023-03-29 23:00:25,657] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:00:25,658] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:00:25,677] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:01:14,265] {processor.py:153} INFO - Started process (PID=9614) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:01:14,266] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:01:14,266] {logging_mixin.py:115} INFO - [2023-03-29 23:01:14,266] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:01:14,278] {logging_mixin.py:115} INFO - [2023-03-29 23:01:14,278] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:01:14,278] {logging_mixin.py:115} INFO - [2023-03-29 23:01:14,278] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:01:14,279] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:01:14,298] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:02:02,696] {processor.py:153} INFO - Started process (PID=9692) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:02:02,696] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:02:02,696] {logging_mixin.py:115} INFO - [2023-03-29 23:02:02,696] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:02:02,710] {logging_mixin.py:115} INFO - [2023-03-29 23:02:02,710] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:02:02,710] {logging_mixin.py:115} INFO - [2023-03-29 23:02:02,710] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:02:02,710] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:02:02,729] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:02:52,482] {processor.py:153} INFO - Started process (PID=9773) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:02:52,482] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:02:52,483] {logging_mixin.py:115} INFO - [2023-03-29 23:02:52,483] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:02:52,495] {logging_mixin.py:115} INFO - [2023-03-29 23:02:52,495] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:02:52,495] {logging_mixin.py:115} INFO - [2023-03-29 23:02:52,495] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:02:52,496] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:02:52,515] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 23:04:02,354] {processor.py:153} INFO - Started process (PID=9891) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:04:02,355] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:04:02,355] {logging_mixin.py:115} INFO - [2023-03-29 23:04:02,355] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:04:02,369] {logging_mixin.py:115} INFO - [2023-03-29 23:04:02,369] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:04:02,369] {logging_mixin.py:115} INFO - [2023-03-29 23:04:02,369] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:04:02,369] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:04:02,388] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:04:51,503] {processor.py:153} INFO - Started process (PID=9973) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:04:51,504] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:04:51,504] {logging_mixin.py:115} INFO - [2023-03-29 23:04:51,504] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:04:51,518] {logging_mixin.py:115} INFO - [2023-03-29 23:04:51,517] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:04:51,518] {logging_mixin.py:115} INFO - [2023-03-29 23:04:51,518] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:04:51,518] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:04:51,537] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:06:00,639] {processor.py:153} INFO - Started process (PID=10087) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:06:00,640] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:06:00,640] {logging_mixin.py:115} INFO - [2023-03-29 23:06:00,640] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:06:00,653] {logging_mixin.py:115} INFO - [2023-03-29 23:06:00,653] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:06:00,654] {logging_mixin.py:115} INFO - [2023-03-29 23:06:00,654] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:06:00,654] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:06:00,674] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:06:47,349] {processor.py:153} INFO - Started process (PID=10165) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:06:47,349] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:06:47,349] {logging_mixin.py:115} INFO - [2023-03-29 23:06:47,349] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:06:47,363] {logging_mixin.py:115} INFO - [2023-03-29 23:06:47,363] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:06:47,363] {logging_mixin.py:115} INFO - [2023-03-29 23:06:47,363] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:06:47,363] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:06:47,383] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:07:55,956] {processor.py:153} INFO - Started process (PID=10278) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:07:55,956] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:07:55,957] {logging_mixin.py:115} INFO - [2023-03-29 23:07:55,957] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:07:55,969] {logging_mixin.py:115} INFO - [2023-03-29 23:07:55,969] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:07:55,969] {logging_mixin.py:115} INFO - [2023-03-29 23:07:55,969] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:07:55,969] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:07:55,988] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-03-29 23:08:44,395] {processor.py:153} INFO - Started process (PID=10367) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:08:44,396] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:08:44,396] {logging_mixin.py:115} INFO - [2023-03-29 23:08:44,396] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:08:44,409] {logging_mixin.py:115} INFO - [2023-03-29 23:08:44,409] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:08:44,409] {logging_mixin.py:115} INFO - [2023-03-29 23:08:44,409] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:08:44,409] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:08:44,429] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:09:45,755] {processor.py:153} INFO - Started process (PID=10480) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:09:45,756] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:09:45,756] {logging_mixin.py:115} INFO - [2023-03-29 23:09:45,756] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:09:45,770] {logging_mixin.py:115} INFO - [2023-03-29 23:09:45,770] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:09:45,770] {logging_mixin.py:115} INFO - [2023-03-29 23:09:45,770] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:09:45,770] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:09:45,790] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:10:40,408] {processor.py:153} INFO - Started process (PID=10569) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:10:40,408] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:10:40,409] {logging_mixin.py:115} INFO - [2023-03-29 23:10:40,409] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:10:40,422] {logging_mixin.py:115} INFO - [2023-03-29 23:10:40,422] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:10:40,422] {logging_mixin.py:115} INFO - [2023-03-29 23:10:40,422] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:10:40,422] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:10:40,441] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:12:04,737] {processor.py:153} INFO - Started process (PID=10726) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:12:04,738] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:12:04,738] {logging_mixin.py:115} INFO - [2023-03-29 23:12:04,738] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:12:04,752] {logging_mixin.py:115} INFO - [2023-03-29 23:12:04,752] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:12:04,752] {logging_mixin.py:115} INFO - [2023-03-29 23:12:04,752] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:12:04,752] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:12:04,771] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:12:59,162] {processor.py:153} INFO - Started process (PID=10832) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:12:59,162] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:12:59,162] {logging_mixin.py:115} INFO - [2023-03-29 23:12:59,162] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:12:59,176] {logging_mixin.py:115} INFO - [2023-03-29 23:12:59,176] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:12:59,176] {logging_mixin.py:115} INFO - [2023-03-29 23:12:59,176] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:12:59,176] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:12:59,195] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:14:11,065] {processor.py:153} INFO - Started process (PID=11008) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:14:11,066] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:14:11,066] {logging_mixin.py:115} INFO - [2023-03-29 23:14:11,066] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:14:11,080] {logging_mixin.py:115} INFO - [2023-03-29 23:14:11,080] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:14:11,081] {logging_mixin.py:115} INFO - [2023-03-29 23:14:11,081] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:14:11,081] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:14:11,101] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:15:06,655] {processor.py:153} INFO - Started process (PID=11097) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:15:06,655] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:15:06,655] {logging_mixin.py:115} INFO - [2023-03-29 23:15:06,655] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:15:06,668] {logging_mixin.py:115} INFO - [2023-03-29 23:15:06,668] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:15:06,668] {logging_mixin.py:115} INFO - [2023-03-29 23:15:06,668] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:15:06,668] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:15:06,687] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 23:16:00,888] {processor.py:153} INFO - Started process (PID=11192) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:16:00,889] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:16:00,889] {logging_mixin.py:115} INFO - [2023-03-29 23:16:00,889] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:16:00,903] {logging_mixin.py:115} INFO - [2023-03-29 23:16:00,902] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:16:00,903] {logging_mixin.py:115} INFO - [2023-03-29 23:16:00,903] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:16:00,903] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:16:00,922] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:16:50,018] {processor.py:153} INFO - Started process (PID=11274) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:16:50,019] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:16:50,019] {logging_mixin.py:115} INFO - [2023-03-29 23:16:50,019] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:16:50,032] {logging_mixin.py:115} INFO - [2023-03-29 23:16:50,032] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:16:50,033] {logging_mixin.py:115} INFO - [2023-03-29 23:16:50,033] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:16:50,033] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:16:50,052] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:17:38,130] {processor.py:153} INFO - Started process (PID=11353) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:17:38,131] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:17:38,132] {logging_mixin.py:115} INFO - [2023-03-29 23:17:38,131] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:17:38,145] {logging_mixin.py:115} INFO - [2023-03-29 23:17:38,145] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:17:38,145] {logging_mixin.py:115} INFO - [2023-03-29 23:17:38,145] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:17:38,145] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:17:38,165] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:18:27,298] {processor.py:153} INFO - Started process (PID=11439) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:18:27,298] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:18:27,299] {logging_mixin.py:115} INFO - [2023-03-29 23:18:27,299] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:18:27,312] {logging_mixin.py:115} INFO - [2023-03-29 23:18:27,311] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:18:27,312] {logging_mixin.py:115} INFO - [2023-03-29 23:18:27,312] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:18:27,312] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:18:27,331] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 23:19:43,129] {processor.py:153} INFO - Started process (PID=11580) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:19:43,129] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:19:43,129] {logging_mixin.py:115} INFO - [2023-03-29 23:19:43,129] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:19:43,144] {logging_mixin.py:115} INFO - [2023-03-29 23:19:43,144] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:19:43,144] {logging_mixin.py:115} INFO - [2023-03-29 23:19:43,144] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:19:43,144] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:19:43,164] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-03-29 23:20:38,570] {processor.py:153} INFO - Started process (PID=11670) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:20:38,571] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:20:38,571] {logging_mixin.py:115} INFO - [2023-03-29 23:20:38,571] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:20:38,585] {logging_mixin.py:115} INFO - [2023-03-29 23:20:38,585] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:20:38,585] {logging_mixin.py:115} INFO - [2023-03-29 23:20:38,585] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:20:38,585] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:20:38,604] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:21:32,924] {processor.py:153} INFO - Started process (PID=11758) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:21:32,925] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:21:32,925] {logging_mixin.py:115} INFO - [2023-03-29 23:21:32,925] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:21:32,939] {logging_mixin.py:115} INFO - [2023-03-29 23:21:32,939] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:21:32,939] {logging_mixin.py:115} INFO - [2023-03-29 23:21:32,939] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:21:32,939] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:21:32,959] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:22:52,200] {processor.py:153} INFO - Started process (PID=11908) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:22:52,201] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:22:52,201] {logging_mixin.py:115} INFO - [2023-03-29 23:22:52,201] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:22:52,214] {logging_mixin.py:115} INFO - [2023-03-29 23:22:52,213] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:22:52,214] {logging_mixin.py:115} INFO - [2023-03-29 23:22:52,214] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:22:52,214] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:22:52,233] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:23:57,561] {processor.py:153} INFO - Started process (PID=12030) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:23:57,562] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:23:57,562] {logging_mixin.py:115} INFO - [2023-03-29 23:23:57,562] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:23:57,575] {logging_mixin.py:115} INFO - [2023-03-29 23:23:57,575] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:23:57,575] {logging_mixin.py:115} INFO - [2023-03-29 23:23:57,575] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:23:57,575] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:23:57,594] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 23:24:51,056] {processor.py:153} INFO - Started process (PID=12117) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:24:51,056] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:24:51,057] {logging_mixin.py:115} INFO - [2023-03-29 23:24:51,057] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:24:51,071] {logging_mixin.py:115} INFO - [2023-03-29 23:24:51,071] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:24:51,071] {logging_mixin.py:115} INFO - [2023-03-29 23:24:51,071] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:24:51,071] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:24:51,096] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2023-03-29 23:25:45,761] {processor.py:153} INFO - Started process (PID=12206) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:25:45,761] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:25:45,761] {logging_mixin.py:115} INFO - [2023-03-29 23:25:45,761] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:25:45,773] {logging_mixin.py:115} INFO - [2023-03-29 23:25:45,773] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:25:45,774] {logging_mixin.py:115} INFO - [2023-03-29 23:25:45,773] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:25:45,774] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:25:45,794] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:26:35,684] {processor.py:153} INFO - Started process (PID=12290) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:26:35,685] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:26:35,685] {logging_mixin.py:115} INFO - [2023-03-29 23:26:35,685] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:26:35,699] {logging_mixin.py:115} INFO - [2023-03-29 23:26:35,699] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:26:35,699] {logging_mixin.py:115} INFO - [2023-03-29 23:26:35,699] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:26:35,699] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:26:35,718] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:27:47,024] {processor.py:153} INFO - Started process (PID=12437) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:27:47,025] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:27:47,025] {logging_mixin.py:115} INFO - [2023-03-29 23:27:47,025] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:27:47,038] {logging_mixin.py:115} INFO - [2023-03-29 23:27:47,038] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:27:47,038] {logging_mixin.py:115} INFO - [2023-03-29 23:27:47,038] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:27:47,038] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:27:47,057] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:28:39,929] {processor.py:153} INFO - Started process (PID=12531) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:28:39,930] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:28:39,931] {logging_mixin.py:115} INFO - [2023-03-29 23:28:39,931] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:28:39,944] {logging_mixin.py:115} INFO - [2023-03-29 23:28:39,944] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:28:39,944] {logging_mixin.py:115} INFO - [2023-03-29 23:28:39,944] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:28:39,944] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:28:39,964] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:29:32,936] {processor.py:153} INFO - Started process (PID=12618) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:29:32,936] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:29:32,936] {logging_mixin.py:115} INFO - [2023-03-29 23:29:32,936] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:29:32,950] {logging_mixin.py:115} INFO - [2023-03-29 23:29:32,950] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:29:32,950] {logging_mixin.py:115} INFO - [2023-03-29 23:29:32,950] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:29:32,950] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:29:32,969] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:30:21,870] {processor.py:153} INFO - Started process (PID=12699) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:30:21,871] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:30:21,871] {logging_mixin.py:115} INFO - [2023-03-29 23:30:21,871] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:30:21,884] {logging_mixin.py:115} INFO - [2023-03-29 23:30:21,884] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:30:21,884] {logging_mixin.py:115} INFO - [2023-03-29 23:30:21,884] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:30:21,884] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:30:21,904] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:31:12,068] {processor.py:153} INFO - Started process (PID=12783) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:31:12,069] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:31:12,069] {logging_mixin.py:115} INFO - [2023-03-29 23:31:12,069] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:31:12,082] {logging_mixin.py:115} INFO - [2023-03-29 23:31:12,082] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:31:12,083] {logging_mixin.py:115} INFO - [2023-03-29 23:31:12,083] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:31:12,083] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:31:12,102] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:32:00,145] {processor.py:153} INFO - Started process (PID=12862) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:32:00,145] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:32:00,145] {logging_mixin.py:115} INFO - [2023-03-29 23:32:00,145] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:32:00,158] {logging_mixin.py:115} INFO - [2023-03-29 23:32:00,158] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:32:00,159] {logging_mixin.py:115} INFO - [2023-03-29 23:32:00,158] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:32:00,159] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:32:00,178] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 23:33:10,320] {processor.py:153} INFO - Started process (PID=13000) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:33:10,321] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:33:10,321] {logging_mixin.py:115} INFO - [2023-03-29 23:33:10,321] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:33:10,335] {logging_mixin.py:115} INFO - [2023-03-29 23:33:10,334] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:33:10,335] {logging_mixin.py:115} INFO - [2023-03-29 23:33:10,335] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:33:10,335] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:33:10,354] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:33:59,796] {processor.py:153} INFO - Started process (PID=13096) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:33:59,796] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:33:59,796] {logging_mixin.py:115} INFO - [2023-03-29 23:33:59,796] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:33:59,810] {logging_mixin.py:115} INFO - [2023-03-29 23:33:59,810] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:33:59,810] {logging_mixin.py:115} INFO - [2023-03-29 23:33:59,810] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:33:59,810] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:33:59,830] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:36:29,055] {processor.py:153} INFO - Started process (PID=13341) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:36:29,056] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:36:29,056] {logging_mixin.py:115} INFO - [2023-03-29 23:36:29,056] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:36:29,070] {logging_mixin.py:115} INFO - [2023-03-29 23:36:29,070] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:36:29,070] {logging_mixin.py:115} INFO - [2023-03-29 23:36:29,070] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:36:29,070] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:36:29,090] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:37:23,533] {processor.py:153} INFO - Started process (PID=13432) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:37:23,534] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:37:23,534] {logging_mixin.py:115} INFO - [2023-03-29 23:37:23,534] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:37:23,547] {logging_mixin.py:115} INFO - [2023-03-29 23:37:23,547] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:37:23,547] {logging_mixin.py:115} INFO - [2023-03-29 23:37:23,547] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:37:23,547] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:37:23,567] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:38:18,672] {processor.py:153} INFO - Started process (PID=13526) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:38:18,673] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:38:18,673] {logging_mixin.py:115} INFO - [2023-03-29 23:38:18,673] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:38:18,687] {logging_mixin.py:115} INFO - [2023-03-29 23:38:18,686] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:38:18,687] {logging_mixin.py:115} INFO - [2023-03-29 23:38:18,687] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:38:18,687] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:38:18,706] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:39:24,493] {processor.py:153} INFO - Started process (PID=13658) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:39:24,494] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:39:24,494] {logging_mixin.py:115} INFO - [2023-03-29 23:39:24,494] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:39:24,508] {logging_mixin.py:115} INFO - [2023-03-29 23:39:24,508] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:39:24,508] {logging_mixin.py:115} INFO - [2023-03-29 23:39:24,508] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:39:24,508] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:39:24,528] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-03-29 23:40:42,704] {processor.py:153} INFO - Started process (PID=13818) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:40:42,705] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:40:42,705] {logging_mixin.py:115} INFO - [2023-03-29 23:40:42,705] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:40:42,718] {logging_mixin.py:115} INFO - [2023-03-29 23:40:42,718] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:40:42,718] {logging_mixin.py:115} INFO - [2023-03-29 23:40:42,718] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:40:42,718] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:40:42,738] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:41:37,251] {processor.py:153} INFO - Started process (PID=13910) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:41:37,251] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:41:37,252] {logging_mixin.py:115} INFO - [2023-03-29 23:41:37,252] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:41:37,265] {logging_mixin.py:115} INFO - [2023-03-29 23:41:37,265] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:41:37,266] {logging_mixin.py:115} INFO - [2023-03-29 23:41:37,266] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:41:37,266] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:41:37,286] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-03-29 23:42:32,811] {processor.py:153} INFO - Started process (PID=14021) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:42:32,812] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:42:32,812] {logging_mixin.py:115} INFO - [2023-03-29 23:42:32,812] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:42:32,826] {logging_mixin.py:115} INFO - [2023-03-29 23:42:32,825] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:42:32,826] {logging_mixin.py:115} INFO - [2023-03-29 23:42:32,826] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:42:32,826] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:42:32,846] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-03-29 23:43:23,250] {processor.py:153} INFO - Started process (PID=14130) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:43:23,251] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:43:23,251] {logging_mixin.py:115} INFO - [2023-03-29 23:43:23,251] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:43:23,265] {logging_mixin.py:115} INFO - [2023-03-29 23:43:23,265] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:43:23,265] {logging_mixin.py:115} INFO - [2023-03-29 23:43:23,265] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:43:23,265] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:43:23,284] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:44:11,412] {processor.py:153} INFO - Started process (PID=14240) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:44:11,412] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:44:11,412] {logging_mixin.py:115} INFO - [2023-03-29 23:44:11,412] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:44:11,426] {logging_mixin.py:115} INFO - [2023-03-29 23:44:11,426] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:44:11,426] {logging_mixin.py:115} INFO - [2023-03-29 23:44:11,426] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:44:11,426] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:44:11,445] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:44:59,832] {processor.py:153} INFO - Started process (PID=14321) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:44:59,832] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:44:59,832] {logging_mixin.py:115} INFO - [2023-03-29 23:44:59,832] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:44:59,845] {logging_mixin.py:115} INFO - [2023-03-29 23:44:59,845] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:44:59,845] {logging_mixin.py:115} INFO - [2023-03-29 23:44:59,845] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:44:59,846] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:44:59,865] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 23:46:10,397] {processor.py:153} INFO - Started process (PID=14484) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:46:10,397] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:46:10,398] {logging_mixin.py:115} INFO - [2023-03-29 23:46:10,398] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:46:10,412] {logging_mixin.py:115} INFO - [2023-03-29 23:46:10,412] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:46:10,412] {logging_mixin.py:115} INFO - [2023-03-29 23:46:10,412] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:46:10,412] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:46:10,433] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-03-29 23:47:20,603] {processor.py:153} INFO - Started process (PID=14629) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:47:20,603] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:47:20,603] {logging_mixin.py:115} INFO - [2023-03-29 23:47:20,603] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:47:20,617] {logging_mixin.py:115} INFO - [2023-03-29 23:47:20,616] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:47:20,617] {logging_mixin.py:115} INFO - [2023-03-29 23:47:20,617] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:47:20,617] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:47:20,636] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:48:12,376] {processor.py:153} INFO - Started process (PID=14725) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:48:12,377] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:48:12,377] {logging_mixin.py:115} INFO - [2023-03-29 23:48:12,377] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:48:12,391] {logging_mixin.py:115} INFO - [2023-03-29 23:48:12,391] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:48:12,391] {logging_mixin.py:115} INFO - [2023-03-29 23:48:12,391] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:48:12,391] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:48:12,411] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:49:01,952] {processor.py:153} INFO - Started process (PID=14810) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:49:01,953] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:49:01,953] {logging_mixin.py:115} INFO - [2023-03-29 23:49:01,953] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:49:01,967] {logging_mixin.py:115} INFO - [2023-03-29 23:49:01,967] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:49:01,967] {logging_mixin.py:115} INFO - [2023-03-29 23:49:01,967] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:49:01,967] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:49:01,986] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:49:51,621] {processor.py:153} INFO - Started process (PID=14891) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:49:51,621] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:49:51,621] {logging_mixin.py:115} INFO - [2023-03-29 23:49:51,621] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:49:51,634] {logging_mixin.py:115} INFO - [2023-03-29 23:49:51,634] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:49:51,634] {logging_mixin.py:115} INFO - [2023-03-29 23:49:51,634] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:49:51,634] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:49:51,653] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-03-29 23:50:55,181] {processor.py:153} INFO - Started process (PID=15039) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:50:55,182] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:50:55,182] {logging_mixin.py:115} INFO - [2023-03-29 23:50:55,182] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:50:55,195] {logging_mixin.py:115} INFO - [2023-03-29 23:50:55,195] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:50:55,195] {logging_mixin.py:115} INFO - [2023-03-29 23:50:55,195] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:50:55,195] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:50:55,215] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:51:50,912] {processor.py:153} INFO - Started process (PID=15138) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:51:50,913] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:51:50,913] {logging_mixin.py:115} INFO - [2023-03-29 23:51:50,913] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:51:50,926] {logging_mixin.py:115} INFO - [2023-03-29 23:51:50,926] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:51:50,926] {logging_mixin.py:115} INFO - [2023-03-29 23:51:50,926] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:51:50,926] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:51:50,946] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:52:46,291] {processor.py:153} INFO - Started process (PID=15248) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:52:46,291] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:52:46,291] {logging_mixin.py:115} INFO - [2023-03-29 23:52:46,291] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:52:46,305] {logging_mixin.py:115} INFO - [2023-03-29 23:52:46,305] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:52:46,305] {logging_mixin.py:115} INFO - [2023-03-29 23:52:46,305] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:52:46,305] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:52:46,324] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:53:35,536] {processor.py:153} INFO - Started process (PID=15369) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:53:35,536] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:53:35,536] {logging_mixin.py:115} INFO - [2023-03-29 23:53:35,536] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:53:35,550] {logging_mixin.py:115} INFO - [2023-03-29 23:53:35,550] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:53:35,550] {logging_mixin.py:115} INFO - [2023-03-29 23:53:35,550] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:53:35,550] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:53:35,569] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:54:27,452] {processor.py:153} INFO - Started process (PID=15454) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:54:27,453] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:54:27,453] {logging_mixin.py:115} INFO - [2023-03-29 23:54:27,453] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:54:27,466] {logging_mixin.py:115} INFO - [2023-03-29 23:54:27,466] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:54:27,466] {logging_mixin.py:115} INFO - [2023-03-29 23:54:27,466] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:54:27,466] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:54:27,486] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2023-03-29 23:55:17,261] {processor.py:153} INFO - Started process (PID=15537) to work on /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:55:17,261] {processor.py:641} INFO - Processing file /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-29 23:55:17,261] {logging_mixin.py:115} INFO - [2023-03-29 23:55:17,261] {dagbag.py:507} INFO - Filling up the DagBag from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:55:17,273] {logging_mixin.py:115} INFO - [2023-03-29 23:55:17,273] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-29 23:55:17,273] {logging_mixin.py:115} INFO - [2023-03-29 23:55:17,273] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-29 23:55:17,273] {processor.py:653} WARNING - No viable dags retrieved from /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-29 23:55:17,292] {processor.py:161} INFO - Processing /Users/gabrielroger/Documents/projects/weather-data/.venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
